##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: msAutenticacion
  devtools:
    add-properties: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/autenticacion
    user: root
    password: postresql
  profiles:
    include:

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: autenticacion
    username: root
    password: postresql